import Header from "./_layout/header";
import Sidebar from "./_layout/sidebar";
import "./globals.css";


export const metadata = {
  title: "Rapid Edit",
  description: "Generated by Clifford Jay Iyac",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Sidebar />
        <div className="pl-[350px] m-12">{children}</div>
      </body>
    </html>
  );
}
